### ISSUE TITLE
[Feature] support curl_multi_exec

### ISSUE THREAD

**Issue by roippi** [DataDog/dd-trace-php#1005]
I noticed there was no tracking issue for this so I made one :). Landing multi-curl auto-instrumentation support would be amazing.

Some mention of supporting this was made recently in curl handler cleanup in https://github.com/DataDog/dd-trace-php/pull/989

Thanks.

**Comment by labbati** [comment]
Hi @roippi, thanks for opening this issue. curl multi support is now possible as all the blocking work is completed. I will ping you here as soon as we will be able to include it into a sprint.

**Comment by labbati** [comment]
Hi @roippi, we added support distributed tracing to curl multi on 0.54.0. Please let me know if this solves your issue or add a comment and I will reopen it, and we can work on a possible improvement to the instrumentation based on your feedback

**Comment by kishanmd** [comment]
Hi, sorry if this is the wrong issue to report this, I've installed dd-trace-php 0.55.0 and I can't seem to get the curl multi tracing to work, the screen in PR https://github.com/DataDog/dd-trace-php/pull/1119 looks like this for me using `distributed-tracing-multi.php`

![image](https://user-images.githubusercontent.com/3974897/108984785-990bfd00-7690-11eb-8f62-b622e24ebb09.png)

phpinfo ddtrace section:

![image](https://user-images.githubusercontent.com/3974897/108984827-a2956500-7690-11eb-9e2b-d6f693abce87.png)

Debug log for the api call:

```
[Wed Feb 24 11:14:23 2021] [::1]:54732 Accepted
[Wed Feb 24 11:14:23 2021] [2021-02-24T11:14:23+01:00] [ddtrace] [debug] - New span web.request  recorded.
[Wed Feb 24 11:14:23 2021] [2021-02-24T11:14:23+01:00] [ddtrace] [debug] - Attempting integrations load
[Wed Feb 24 11:14:23 2021] [2021-02-24T11:14:23+01:00] [ddtrace] [debug] - Loaded integration web
[Wed Feb 24 11:14:23 2021] [2021-02-24T11:14:23+01:00] [ddtrace] [debug] - Loaded integration cakephp
[Wed Feb 24 11:14:23 2021] [2021-02-24T11:14:23+01:00] [ddtrace] [debug] - Loaded integration codeigniter
[Wed Feb 24 11:14:23 2021] [2021-02-24T11:14:23+01:00] [ddtrace] [debug] - Loaded integration curl
[Wed Feb 24 11:14:23 2021] [2021-02-24T11:14:23+01:00] [ddtrace] [debug] - Loaded integration eloquent
[Wed Feb 24 11:14:23 2021] [2021-02-24T11:14:23+01:00] [ddtrace] [debug] - Loaded integration guzzle
[Wed Feb 24 11:14:23 2021] [2021-02-24T11:14:23+01:00] [ddtrace] [debug] - Loaded integration laravel
[Wed Feb 24 11:14:23 2021] [2021-02-24T11:14:23+01:00] [ddtrace] [debug] - Loaded integration lumen
[Wed Feb 24 11:14:23 2021] [2021-02-24T11:14:23+01:00] [ddtrace] [debug] - Integration mongo not available. New attempts WILL NOT be performed.
[Wed Feb 24 11:14:23 2021] [2021-02-24T11:14:23+01:00] [ddtrace] [debug] - Integration mysqli not available. New attempts WILL NOT be performed.
[Wed Feb 24 11:14:23 2021] [2021-02-24T11:14:23+01:00] [ddtrace] [debug] - Loaded integration symfony
[Wed Feb 24 11:14:23 2021] [2021-02-24T11:14:23+01:00] [ddtrace] [debug] - Loaded integration zendframework
[Wed Feb 24 11:14:23 2021] [::1]:54732 [200]: GET /api.php?group=blue
[Wed Feb 24 11:14:23 2021] [2021-02-24T11:14:23+01:00] [ddtrace] [debug] - Flushing 1 traces, 3 spans
[Wed Feb 24 11:14:23 2021] [2021-02-24T11:14:23+01:00] [ddtrace] [debug] - Encoding span '8022020164097351682' op: 'web.request' serv: 'web.request' res: 'GET /api.php' type 'web'
[Wed Feb 24 11:14:23 2021] [2021-02-24T11:14:23+01:00] [ddtrace] [debug] - Tags for span 8022020164097351682 'tag:chars_count' are: http.method:3,http.url:8,http.status_code:3
[Wed Feb 24 11:14:23 2021] [2021-02-24T11:14:23+01:00] [ddtrace] [debug] - About to send trace(s) to the agent
[Wed Feb 24 11:14:23 2021] [::1]:54732 Closing
```


The odd part is that `distributed-tracing.php` and `distributed-tracing-multi-guzzle.php` do show a split in the individual requests:

![image](https://user-images.githubusercontent.com/3974897/108987217-513aa500-7693-11eb-8416-72d80ac32321.png)

![image](https://user-images.githubusercontent.com/3974897/108987235-5566c280-7693-11eb-93bf-47b8f227e4b9.png)


What could cause this to be the case? Since my application also does not show the underlying requests, just like `distributed-tracing-multi.php`.

If I need to move this let me know!

**Comment by SammyK** [comment]
Thanks for reporting this issue @kishanmd. We can reproduce this issue on our end and will investigate this further. In the meantime, would you mind opening a new issue to report this? Thanks again!

**Comment by kishanmd** [comment]
@SammyK of course, see https://github.com/DataDog/dd-trace-php/issues/1156, good to hear it's not only me!
