### ISSUE TITLE
Are request query params in traces / spans supported out of the box?

### ISSUE THREAD

**Issue by mirfilip** [DataDog/dd-trace-php#1270]
Hi,
it's neither a bug or a feature request, more an overall question I couldn't find the answer for in the docs.

Does this integration handle query params / query string of a main request? Are they kept in traces / spans?

Background: I have a service based on Zend Framework 2 where query params is a very handy knowledge when inspecting traces. Apart from some automatically extracted path params (think ZF2 routing), there is not much more. For one, query params that are part of the main request are nowhere to be found in DD UI dashboards. 

Do I have to manually instrument it to have them saved with spans or is this something that should happen automatically?

As an extra question: what about the same thing but for sub-requests to external http resources that happen during the main request? Is it possible to have query params saved there too?

**Comment by labbati** [comment]
Hi. As of today we are not storing anywhere query string params to avoid leaking potentially confidential data (think of some APIs accepting tokens in query string params).

In the meantime you can do some manual tracing. For example, a possible approach is to set all the interesting query string params in your `index.php`, as when your `index.php` is executing, the [active span](https://docs.datadoghq.com/tracing/setup_overview/custom_instrumentation/php?tab=tracingfunctioncalls#accessing-active-spans) is the root span

In the long term, there are 2 use cases that involves query string parameters and that we are considering supporting: (1) is for spans' resource names and (2) to have the full list of query string params in order to help debugging issues. I guess you are more interested in (2), but let me expand on both.

1. Some frameworks have a unique entry point and then base routing on query string params, e.g. `/some/entry-point?view=product-list&some_key=value`. As of today, we normalize this resource name to `GET /some/entry-point` meaning that users loose track of which route caused a problem. To solve this very specific problem we agreed to provide a configuration setting `DD_TRACE_QUERY_STRING_RESOURCE_PARAMS=wc-api,wc-ajax,view` where users can specify a pass-list of names that will be used to form the resource name, that for our example would become `GET /some/entry-point?view=product-list`.
2. This is more tricky, since it would require a flag to store ALL query string params as metadata (it would be impossible to ask users to add all interesting query names one by one) and possibly an additional setting with a stop-list of names (e.g. `api_token`). If you are in this use case, would you find this approach useful? Note that potentially ALL ON + stop-list can easily cause leak of confidential data stored in query string parameters to the UI.

**Comment by mirfilip** [comment]
> Hi. As of today we are not storing anywhere query string params to avoid leaking potentially confidential data (think of some APIs accepting tokens in query string params).

Well, there's already a [mechanism of replacing sensitive data in tags](https://docs.datadoghq.com/tracing/setup_overview/configure_data_security), so there is a facility in place to use to avoid confidential data leaks. If there's some default list with well known query params that store secrets, that would handle this problem.

> In the meantime you can do some manual tracing. For example, a possible approach is to set all the interesting query string params in your `index.php`, as when your `index.php` is executing, the [active span](https://docs.datadoghq.com/tracing/setup_overview/custom_instrumentation/php?tab=tracingfunctioncalls#accessing-active-spans) is the root span

That's what I meant by "manually setting query param as tags". Yes, a viable workaround, but it scales nastily. Having a big API, I don't really know all the context to decide which query params to store in `index.php`. It's a per endpoint decision, so we end up writing a custom middleware for each endpoint. Not good, cumbersome to maintain. I believe APMs should be as plug-and-play to use as possible.

> 2. This is more tricky, since it would require a flag to store ALL query string params as metadata (it would be impossible to ask users to add all interesting query names one by one) and possibly an additional setting with a stop-list of names (e.g. `api_token`). If you are in this use case, would you find this approach useful? Note that potentially ALL ON + stop-list can easily cause leak of confidential data stored in query string parameters to the UI.

My take on this: as mentioned above, if there is a well known list of "problematic" query params (ideally an open source thing, maybe even stored in this repo so that people can contribute) + a global switch to toggle this feature, I don't see a problem. There could be two switches: feature toggle to parse all query params + feature toggle to use a blacklist (by default that well known problematic list), then you're safe. It could even be default off. In that scenario, me as a user would turn this on and use a default blacklist and tweak it if I find security problems with what I send to DD.

I've been using NewRelic for many years and they have [a similar mechanism in place](https://docs.newrelic.com/docs/agents/php-agent/attributes/attribute-examples/)
