### ISSUE TITLE
Laravel breaks when application/package uses the pipeline class

### ISSUE THREAD

**Issue by stayallive** [DataDog/dd-trace-php#157]
So I noticed the Laravel integration "hi-jacks" the Pipeline class to detect / measure the middleware, however... this class is _not_ specific for middleware :)

![image](https://user-images.githubusercontent.com/1090754/49251080-e0a76e00-f420-11e8-8054-341713354d7a.png)

As you can see Lighthouse (a GraphQL package) for example uses the Pipeline quite a bit and at best it will cause some extra middleware that are not middleware... but at worst as in this case it crashed since the `handle` method is hardcoded in the integration, but on the pipeline its dynamic 😄 

I tried to find a good way around it but there is a lot going on in that little L5 service provider and not sure how the dd_trace function works etc. etc.

So leaving this here so it can be figured out 👍 

I will disable dd-trace for now (perks of joining them sweet, sweet beta's)

**Comment by labbati** [comment]
Hi @stayallive thanks for filing the issue and sorry to hear of this problem you had with pipelines.

I went through the code for versions 5.7, 5.6 and 5.5 and it looks to me that the only way a user can modify the handler's method name is through `via` [here](https://github.com/laravel/framework/blob/d0e1331227e8acd68177760d85b4bac399bef757/src/Illuminate/Pipeline/Pipeline.php#L85).

If this is confirmed, (will investigate some more) I would say the fix can be:

 - Instead of using [`through`](https://github.com/DataDog/dd-trace-php/blob/921f290ab1d2d02c05caf0a2efa15650db9bd5fe/src/DDTrace/Integrations/Laravel/V5/LaravelProvider.php#L68) as an hook we can use [`then`](https://github.com/laravel/framework/blob/5.7/src/Illuminate/Pipeline/Pipeline.php#L98):
 - There we have access to both `$pipes` and the `$method` name that must have been set by that time, and we will use it to instrument the correct method of the `$pipe`
 - we also mark that particular `Pipeline` instance has "already instrumented", so we make sure that we are not instrumenting twice.

We will start looking into it and to promptly provide a fix, but in the meantime I wanted to share this plan with the community so if anyone as any feedback can share. And feel free to suggest a more appropriate approach is it comes to your mind.

Thanks for the patience during this beta phase!

**Comment by stayallive** [comment]
Hi @labbati, thanks for looking into it!

I'm pretty sure that the pipeline for the http request will be the first pipeline in the application, however, that might change in the future or by some package. So depending on the first pipeline being the pipeline you're looking for might break in the end to.

As you can see here https://github.com/nuwave/lighthouse/blob/1e22446cdd27b6eccf86b2008dfda9e06917603b/src/Schema/Factories/FieldFactory.php#L71-L82 it's for example used to provide "middleware" for a object and has very little to do with the request middlewares. This runs in the request but also could run in a serviceprovider making it a pipeline instance that runs before the request middleware pipeline.

The fix looks (after a quick glance) like it should work regarding reading the correct `$method`.

**Comment by labbati** [comment]
Hi,

> I'm pretty sure that the pipeline for the http request will be the first pipeline in the application, however, that might change in the future or by some package. So depending on the first pipeline being the pipeline you're looking for might break in the end to.

I am not sure I am following. The `then()` hook would be called at least once per pipeline instance, so if I have ten pipelines used in the app, then the `then()` hook will be called at least ten times. And each pipeline can have a different handler method name. When I say "we make sure that we are not instrumenting it twice" I mean the very same instance of a pipeline. Even if the same pipeline is called 2 times, we would still have to instrument once and then trace twice. Am I misunderstanding your comment?

> As you can see here https://github.com/nuwave/lighthouse/blob/1e22446cdd27b6eccf86b2008dfda9e06917603b/src/Schema/Factories/FieldFactory.php#L71-L82 it's for example used to provide "middleware" for a object and has very little to do with the request middlewares. This runs in the request but also could run in a serviceprovider making it a pipeline instance that runs before the request middleware pipeline.

Not very familiar with Pipelines in Laravel, but looking at the code that you linked it looks like the approach that I was proposing would work, even is the same pipeline is used multiple times. If you don't fell like this then I need a little bit more context.

> The fix looks (after a quick glance) like it should work regarding reading the correct $method.
I think I am not following here, how can work "regarding reading the correct $method"?

Sorry for all those "I am not following", I am sure I miss a tiny bit that will clarify it all to me. 😄

**Comment by stayallive** [comment]
Ah, I think I was thinking only the HTTP middlewares are/should be instrumented but you want to add instrumentation to all pipeline instances 👍 

I interpreted this `laravel.middleware` as http/route middleware.

https://github.com/DataDog/dd-trace-php/blob/921f290ab1d2d02c05caf0a2efa15650db9bd5fe/src/DDTrace/Integrations/Laravel/V5/LaravelProvider.php#L94

Although I'm not sure how useful data from all pipelines in an application would be, your approach does looks like it will work to profile them.

I probably just explained it terrible 😄

**Comment by labbati** [comment]
Ah ok, now I get it. The name is not appriopriate actually, you are right. Let's rename it and keep this approach for now.
Thanks

**Comment by labbati** [comment]
Hi! Version [0.5.1](https://github.com/DataDog/dd-trace-php/releases/tag/0.5.1) is out which brings the fix we discussed in this thread. It would be great if you have a chance to test it and to give us some feedback.

Thanks!

**Comment by labbati** [comment]
Hi @stayallive! I am just curious, did you have a chance to test the new version to make sure the problem is fixed?

**Comment by stayallive** [comment]
I just deployed with the change and it looks good 👍 no more crashed!

**Comment by labbati** [comment]
Awesome news! Thanks for the patience, and sorry for the issues that you experimented.

**Comment by stayallive** [comment]
No problem, that's were the beta tag is for!
