### ISSUE TITLE
[Feature] symfony 6 support?

### ISSUE THREAD

**Issue by kissifrot** [DataDog/dd-trace-php#1744]
**Is your feature request related to a problem? Please describe.**
Refering to the [docs,](https://docs.datadoghq.com/tracing/trace_collection/compatibility/php/#web-framework-compatibility) symfony 6 is not supported
Looks like we do not get any spans/errors when using symfony 6 commands, but other traces works correctly

**Describe the solution you'd like**
Full support for symfony 6 🙂

**Comment by bwoebi** [comment]
Hey @kissifrot,

we've just run our Integrations against Symfony 6 and found nothing which changed in the completeness of the symfony integration.

It is true, that the docs explicitly mentioned 5.x, but that's just because it was not tested against.
Unless you encountered specific issues, we would just update our docs?

Thanks!

**Comment by kissifrot** [comment]
> Hey @kissifrot,
> 
> we've just run our Integrations against Symfony 6.0 and found nothing which changed in the completeness of the symfony integration.
> 
> It is true, that the docs explicitly mentioned 5.x, but that's just because it was not tested against. Unless you encountered specific issues, we would just update our docs?
> 
> Thanks!

Hello @bwoebi , yes just a docs update would do the job 👍

**Comment by bwoebi** [comment]
Then closing this, as the relevant documentation change has been merged: https://github.com/DataDog/documentation/pull/16637.
