### ISSUE TITLE
[BUG] Monolog 3 `dd.trace_id` / `dd.span_id` not available as top level log entries

### ISSUE THREAD

**Issue by matthewnessworthy** [DataDog/dd-trace-php#1950]
### Bug description
With MonoLog 3 it is no longer possible to set attributes in the top level of the log record when using JSON.

```
$monolog->pushProcessor(function ($record) {
            $context = \DDTrace\current_context();
            $record['dd'] = [
                'trace_id' => $context['trace_id'],
                'span_id'  => $context['span_id'],
            ];
```
MonoLog LogRecord https://github.com/Seldaek/monolog/blob/main/src/Monolog/LogRecord.php
DataDog docs https://docs.datadoghq.com/logs/log_collection/php/?tab=laravel#laravel

### PHP version
```
PHP 8.1.15 (cli) (built: Feb  3 2023 12:35:11) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.15, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.15, Copyright (c), by Zend Technologies
```

### Tracer version
NA

### Installed extensions
NA

### OS info
NA

#### Output of phpinfo() (ddtrace >= 0.47.0)
NA

#### Output of dd-doctor (ddtrace < 0.47.0)
NA

### Upgrading info
NA

**Comment by bwoebi** [comment]
Hey @matthewnessworthy,

reading that file, I suppose all custom information is to be included in the `['extra']` key now, i.e. `$record['extra']['dd'] = [...];`. Would that work?

**Comment by matthewnessworthy** [comment]
Yes, as long as dd can pull the trace_id and span_if from the non-standard payload (by that i mean, not the one documented)

**Comment by deegital** [comment]
Is this a solution, will it be picked up from the extra data already?

As monolog 3 is a dependency of laravel 10, this is currently a blocker for upgrading :/

@matthewnessworthy maybe you can edit the title of the issue to include monolog 3

**Comment by PROFeNoM** [comment]
Hey there :wave: I tested on a local app about a month ago using this newly introduced `extra` field in the `LogRecord`, and I can confirm this is working fine. I modified the [manual injection](https://docs.datadoghq.com/tracing/other_telemetry/connect_logs_and_traces/php/#manual-injection) doc, but overlooked and didn’t modify the [log collection](https://docs.datadoghq.com/logs/log_collection/php/?tab=laravel#laravel) one, mb!

Therefore, yes, you should be able to set these extra attributes using either `$record->extra['dd’]` or `$record['extra']['dd’]` instead of `$record['dd’]` for Monolog v3. Let me know if you need anything else :hammer_and_wrench:
