### ISSUE TITLE
PHP < 5.6 compatibility

### ISSUE THREAD

**Issue by remicollet** [DataDog/dd-trace-php#213]
Don't known if you really want to support php < 5.6, but package.xml states minimal version is 5.4

Build fails with 5.4 and 5.5

Please clarify

**Comment by SammyK** [comment]
Thanks @remicollet! That was a type-o in the package.xml when I pushed the release to PECL. It should be PHP 5.6. I have [since fixed it in the XML](https://github.com/DataDog/dd-trace-php/pull/210/files), but I can't seem to overwrite the release. Is that possible in PECL or do we need to tag another minor release? :)

**Comment by SammyK** [comment]
Makes sense - thanks. We have another release scheduled for Monday so we should be able to get everything sorted for that. :)

**Comment by labbati** [comment]
@SammyK I think that this has been fixed?

**Comment by SammyK** [comment]
@labbati Yep! The `package.xml` now has PHP 5.6 as the minimum PHP version. :)
