### ISSUE TITLE
[Bug]: Cannot BUILD on RHEL 8.8 and 9.2

### ISSUE THREAD

**Issue by remicollet** [DataDog/dd-trace-php#2249]
### Bug report

* RHEL 9.2 have rust 1.66.1
* RHEL 8.8 have rust 1.66.1

But this project now requires 1.70 (clap, clap_builder and clap_lex)

CentOS Stream has 1.71, but don't know which exact version will  be in next RHEL point release 8.9 and 9.3

Also affects all RHEL clones (AlmaLinux, RockyLinux, OEL...)

### PHP version

irrelevant

### Tracer or profiler version

0.91.0

Dependencies grow from 321M to 386M :(

Again rust seems incompatible with Enterprise distribution with low update rate :(

**Comment by bwoebi** [comment]
Hey Remi,

is this a fundamental issue for you, or would it be possible to fetch the latest rustup from the official sources, i.e. https://doc.rust-lang.org/cargo/getting-started/installation.html?

It's just needed for building, so not a dependency of the built objects.

**Comment by remicollet** [comment]
> would it be possible to fetch the latest rustup from the official sources

no, again, in RPM build we can only use what is available as RPM, and build are run offline
(and obviously I don't want to manage the rust build)

> is this a fundamental issue for you, 

I'm able to workaround the issue using CentOS Stream as builder, but this may raise some other issues
(I usually only use official RHEL)

So this is mostly for your information
and if other RHEL users try to install this extension manually.


Perhaps I should consider stop fighting with some extension packaging, especially when it generates headaches
(and is time consuming... >4h for this one)

**Comment by morrisonlevi** [comment]
It looks like RHEL 8.x has been bumping the Rust toolchain by about 4 minors per release. This seems like they are roughly tracking the latest Rust, just lagged slightly. If this roughly holds true, then the policy I outlined in the previous point will _hopefully_ work for building on RHEL, or at least should be pretty close.

**Comment by remicollet** [comment]
> It looks like RHEL 8.x has been bumping the Rust toolchain by about 4 minors per release. This seems like they are roughly tracking the latest Rust, just lagged slightly.

No.

As said previously

* **RHEL 9.0** have 1.58 (EUS until May 31th 2024)
* **RHEL 9.1** have 1.62 (EOL)
* **RHEL 9.2** have 1.66 (supported until 9.3 release and EUS until May 31 2025)
* **CentOS 9** Stream have 1.71.1

So RHEL 9.3 (probably to be released this autumn) will probably have something >= 1.70

So for now, CentOS is OK, RHEL is not.

Again, it looks like rust update rate is really incompatible with enterprise distribution.

See
* [Available rust versions](https://rpms.remirepo.net/rpmphp/zoom.php?rpm=rust)
* [Red Hat Enterprise Linux Life Cycle](https://access.redhat.com/support/policy/updates/errata/)

**Comment by morrisonlevi** [comment]
Ah, I had a bad assumption. I assumed we only need to build on the latest of 8.x and 9.x, not all 8.x and 9.x versions.

I will think about this more. At the moment, I don't think it's worth downgrading Rust versions, especially because I know some of the version bumps were required for things. Maybe we could be more cautious going forward, though.

I don't really know how many users you are helping. I don't know how to tell how many installs there are of your package, and how many of them aren't your own package-builders and tests and things. If you have numbers that can be shared, it would be interesting to see how many users are using what dd-trace-php versions. Maybe you can shift to a different packaging strategy for dd-trace-php? Version pinning is somewhat common on these older distros (I used to use RHEL 6 and 7, and we had to ping stuff at least), so maybe just build the latest version which still builds for those older releases?

**Comment by remicollet** [comment]
> Ah, I had a bad assumption. I assumed we only need to build on the latest of 8.x and 9.x, not all 8.x and 9.x versions.

It's probably fine to ignore EUS versions (very few users, and not the one wanting updates)

> I don't really know how many users you are helping.

Quite a lot. Hard to know.
Other 3rd party repositories (webtatic, IUS...) have forgiven.
I have some download numbers
* https://blog.remirepo.net/post/2023/09/01/PHP-version-8.1.23-and-8.2.10
* https://blog.remirepo.net/pages/PECL-extensions-RPM-status#c10421

But these numbers are only **useful to compare** ext success, there are downloads done by people aspiring the whole site, but also missing numbers from some mirrors, especially private ones (usually big sites with lot of servers).

**Comment by remicollet** [comment]
New point releases are available for RHEL, AlmaLinux, RockyLinux...

* RHEL **9.3** with **rust 1.71.1**
* RHEL **8.9** with **rust 1.71.1**
* RHEL-7 doesn't have rust but EPEL provides 1.72.1

Notice CentOS Stream has 1.73 (so this will probably be part of 8.10/9.4)
For memory: https://rpms.remirepo.net/rpmphp/zoom.php?rpm=rust

So closing, but please try to avoid raising the dependency ;)

**Comment by morrisonlevi** [comment]
Thanks for this information. To make sure I understand the implications, if we changed our minimum Rust version (MSRV) from 1.69 to 1.71, this would not impact your current builds? Asking partly because depending on what's decided with this info, we may be on this MSRV for a long time, so it'd be nice to have the absolutely highest possible one if that happens.

**Comment by remicollet** [comment]
> if we changed our minimum Rust version (MSRV) from 1.69 to 1.71, this would not impact your current builds? 

Exactly.
My build and any user building from sources on RHEL / CentOS / Alma / Rocky / OEL...


P.S. it is already 1.70 (not 1.69) which is required (probably because of some dep)
