### ISSUE TITLE
Integration with Moodle LMS

### ISSUE THREAD

**Issue by nadavkav** [DataDog/dd-trace-php#229]
Hello Developers,

I am using the php based Moodle LMS framework.
I am struggling with adding APM tracing into Moodle

Here is a link to the project's github account:
https://github.com/moodle/moodle/
The main include file is config.php

Can you help and give advise, how to go about adding APM tracing into Moodle?

Kindly,
Nadav

**Comment by labbati** [comment]
Hi @nadavkav, thanks for bringing Moodle LMS to our attention and welcome to the community 😄.

Unfortunately, at the moment we have no plans to support it officially, as we are totally focus on transitioning from beta to GA.
However, if you install the latest release, we added basic framework-independent web requests instrumentation even for frameworks that we do not support. With this in place you will have traces for each web requests (with relevant metadata such as url, method, status code, etc...) and all the usual traces from our integrations, e.g. PDO, mysqli, ...

Of course you will not have any Moodle-specific method tracing, but if you are interested in some specific method invocation you can always instrument that specific method in you code. In order to do that you can decide to use the [Datadog API](https://docs.datadoghq.com/tracing/advanced_usage/?tab=php#manual-instrumentation) or the [OpenTracing API](https://docs.datadoghq.com/tracing/advanced_usage/?tab=php#opentracing).

Closing this issue now but feel free to re-open it if you need further assistance.

**Comment by nadavkav** [comment]
Hello @labbati ,
Thank you for your reply. Indeed, I am aware of the beta stage of this code and the availability for formal support to integrate it with new frameworks.

Before opening this issue, I was already using your DD generic instrumentation to capture some tracing which was very useful, but I was looking for a more tight integration (like the one I currently have with one of the other tools I am currently using Blackfire, Rollbar, Sentry,  and looking to drop them)
One that enables a waterfall of function call tracing.

I was actually looking for some advice in case you can look into the Moodle code and direct me to the proper way of adding the DD API trace functions in the right places, and maybe using Moodle's shutdown function instead of the generic register_shutdown_function.

Again, thank you!
