### ISSUE TITLE
CircleCI integration doesn't work

### ISSUE THREAD

**Issue by localheinz** [DataDog/dd-trace-php#26]
As of the moment, all pull requests are waiting for CircleCI to kick in, but it doesn't.

For example, see #23:

![screen shot 2018-07-03 at 09 34 40](https://user-images.githubusercontent.com/605483/42205304-5ed828c0-7ea4-11e8-8c44-e1a2fb9bd758.png)

Also see #21.

**Comment by chuck** [comment]
I'll do #21 and make sure that everything is working after.

**Comment by chuck** [comment]
Actually we're already on CircleCI 2, but something else is up.

**Comment by chuck** [comment]
Looks to be working for new pushes now. Trying to find a way to get it to re-run for the existing PRs.

**Comment by chuck** [comment]
After poking a bit more, I'm pretty sure the issue was actually that running builds for PRs from forks was turned off in the Circle CI configuration. I've fixed that. Unfortunately there doesn't seem to be any way to manually re-trigger those workflows, but given that the changes are small and the project is still very early/experimental, I'm going to go ahead and merge them one-by-one and let the master tests run and verify the changes.

**Comment by localheinz** [comment]
Thank you, @chuck!
