### ISSUE TITLE
[Bug] Crashes on 1.5.0

### ISSUE THREAD

**Issue by jr-k** [DataDog/dd-trace-php#2966]
### Bug report

Hello,

Since this morning, the datadog-ipc-helper process has been crashing repeatedly in our Kubernetes environment, causing significant instability in our production system. My Dockerfile was configured to use the latest tag, which pulled the new version during deployment and led to these crashes.

I understand that version 1.5.0 is marked as having this known issue, but I find it concerning that a minor release introduces such a major problem. This has severely impacted our production environment, and I believe such changes should be handled with more caution.

Please advise on any workaround or hotfix to address this issue. Let me know if you need additional details or logs to investigate.

### PHP version

8.2.19

### Tracer or profiler version

latest

**Comment by Anilm3** [comment]
Hey @jr-k,

This is unfortunate, but we have identified the root cause of the crash and are currently in the process of fixing it and releasing a patch.

The only workaround at the moment is to downgrade to the previous version which is [v1.4.2](https://github.com/DataDog/dd-trace-php/releases/tag/1.4.2).

We'll let you know once the patch release containing the fix is available.

**Comment by bwoebi** [comment]
@jr-k Also do add to this, the bug does only affect arm64, but only with the release build. We did test on arm64, but not with the release build. We do test with the release build, but that one was only tested with amd64.

I'm sorry for the inconvenience caused by this gap in our test matrix. As Anil said, we'll release a new version soon.

**Comment by Anilm3** [comment]
Hey @jr-k, @rokclimb15,

We've just released the fix in https://github.com/DataDog/dd-trace-php/releases/tag/1.5.1, thanks for your understanding and please let us know if you experience any other issues.
