### ISSUE TITLE
Support for baggage items

### ISSUE THREAD

**Issue by tinrab** [DataDog/dd-trace-php#298]
I've tried adding a few baggage items to a trace with `Span::addBaggageItem`, but they're not visible on the APM dashboard. Through debugging, I've found that they're not actually being sent to the agent: https://github.com/DataDog/dd-trace-php/blob/master/src/DDTrace/Encoders/Json.php#L116. Is this feature WIP or am I missing something?

**Comment by labbati** [comment]
Hi @tinrab 👋, and sorry for the late reply.
This is actually a bug and we will work on this very soon! At the moment, for the next few days, we are totally focused on making the library stable in all the possible usage scenarios.
Thanks!

**Comment by ajessu** [comment]
@labbati Was exploring on addressing this.
Does the baggage items in a span appear on the APM UI?

Meant to play with the Ruby tracer, which seems one of the most complete on this regard to double check after having no success with the php (as reported) nor python one.

From what I've had the chance to read, mainly from [here](https://opentracing.io/docs/overview/inject-extract/), [here](https://opentracing.io/docs/best-practices/instrumenting-frameworks/) and [here](https://opentracing.io/docs/best-practices/#extracting-a-spancontext-from-an-incoming-request), if I'm understanding correctly: the baggage items are mostly for inter process/service communications. As in, distributed tracing between separate services, to be able to keep context between then, and they are meant to be explicitly injected and extracted.

Curious: is there any other use, in the context of what you consider this a bug, where this would need to be included as part of any structure or agent api data so that it shows on the UI?

### For extra reference
#### Jaeger only shows it on the original span

https://github.com/jaegertracing/jaeger-client-java/issues/267#issuecomment-335504127
> We only log the baggage item when it gets set/updated which is why you see it in the UI (this is for visibility into when and where it got set). The receiver span will still have the baggage on it but it won't be logged in the UI

#### Python tracer:
Ran the python example on the trace-examples repo, [which includes baggage items](https://github.com/DataDog/trace-examples/blob/0ee1d2d0db8ef658b701ae4a4d92b398fc5a84eb/python/opentracing/laundry/laundry.py#L79-L80), but didn't see them on the UI.
Guessing it has to do [with this comment](https://github.com/DataDog/dd-trace-py/pull/497#discussion_r198894584), but not sure if that comment is still relevant:
> we should not set this as tags because `baggage` != `tag`. Our platform should not receive baggage values right now.

If they do show on the UI, do you have any examples to trigger those or if they'd show up adjacent to tags of a span?

**Comment by bwoebi** [comment]
I am closing this issue, as Datadog tracers generally do not export baggage.

Baggage is a concept to attach data to spans for local processing during manual instrumentation. Metadata which shall be exported needs to be added to spans as tag or metric.

**Comment by umarkhan17** [comment]
We would want to send baggage items to datadog, how do we achieve this?
