### ISSUE TITLE
Predis Integration exception

### ISSUE THREAD

**Issue by ynuyasha** [DataDog/dd-trace-php#315]
Hi,
if i enable ddtrace module, my application breaks with this error:

Recoverable Error: Object of class Predis\Connection\Aggregate\MasterSlaveReplication could not be converted to string (File: /opt/datadog-php/dd-trace-sources/src/DDTrace/Integrations/Predis/PredisIntegration.php - Line: 171)

**Comment by labbati** [comment]
Hi @ynuyasha 👋 , thanks for reporting this. Not sure if you are interested in it, but if you like to contribute this would be a very good first issue. Otherwise, we will work on it as soon as possible.

In the meantime, you can still use all the other integrations and disable only Predis `DD_INTEGRATIONS_DISABLED=false` (see [docs](https://docs.datadoghq.com/tracing/languages/php/#configuration))

**Comment by bwoebi** [comment]
This has been fully fixed by #574 and then as part of #1094.
