### ISSUE TITLE
Array to string conversion in ElasticSearchIntegration

### ISSUE THREAD

**Issue by tot-ra** [DataDog/dd-trace-php#336]
Seems that this part in `buildResourceName()` assumes that params['index'] is plain string.. but I seem to get it as array
> $resourceFragments[] = $relevantParamName . ':' . $params[$relevantParamName];

https://github.com/DataDog/dd-trace-php/blob/master/src/DDTrace/Integrations/ElasticSearch/V1/ElasticSearchIntegration.php#L313

So I get
```js
"error":"Array to string conversion", 
"backtrace":[{
"file":"\/var\/app\/vendor\/datadog\/dd-trace\/src\/DDTrace\/Integrations\/ElasticSearch\/V1\/ElasticSearchIntegration.php",
"line":189,
"function":"buildResourceName",
"class":"DDTrace\\Integrations\\ElasticSearch\\V1\\ElasticSearchIntegration",
"type":"::",
"args":["search",{"index":["deal","org","file","person","product","mail_attachment","note"],
"body":{"query":{"function_score...":
```

**Comment by labbati** [comment]
Hi! Thanks for reporting this. Which version of Elastic Search client library are you using?

**Comment by labbati** [comment]
After a brief investigation.

In elastic search params `index` and `type` can be provided to the client both as string and array: [index](https://github.com/elastic/elasticsearch-php/blob/master/src/Elasticsearch/Endpoints/AbstractEndpoint.php#L119), [type](https://github.com/elastic/elasticsearch-php/blob/master/src/Elasticsearch/Endpoints/AbstractEndpoint.php#L148).

In our integration we read the values from the `$params` provided by the users  [here](https://github.com/DataDog/dd-trace-php/blob/9f9c70024ec330c9c7a83706bd9229604a997908/src/DDTrace/Integrations/ElasticSearch/V1/ElasticSearchIntegration.php#L300) instead of accessing them trough the client's getters, where they would be normalized instead.

We should change this behavior to be more robust.

We will work on that asap, in the meantime any help would be welcomed.

One side note: if while we fix this you would like to keep using our tracer for other integrations, you could still disable only elastic search: `DD_INTEGRATIONS_DISABLED=elasticsearch`

**Comment by labbati** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[#336] ElasticSearch integration error](https://trello.com/c/6qJqfXwA/1576-336-elasticsearch-integration-error)

**Comment by ctrlrsf** [comment]
I'm also seeing this same "Array to string conversion" error, but at a different line number. For now we have the integration disabled, but would like to have this fixed so we can properly evaluate APM. Please let me know if you need any additional info from me to look into this further. Thanks!

datadog-php-tracer version is 0.19.1

```
{
    "errno": 8,
    "errstr": "Array to string conversion",
    "errfile": "/opt/datadog-php/dd-trace-sources/src/DDTrace/Integrations/ElasticSearch/V1/ElasticSearchIntegration.php",
    "errline": 338,
    "file": "/opt/datadog-php/dd-trace-sources/src/DDTrace/Integrations/ElasticSearch/V1/ElasticSearchIntegration.php",
    "line": 338
}
```

**Comment by labbati** [comment]
Hi @ctrlrsf! I am closing this very old issue as we completely re-designed our integrations to avoid errors like this. If you upgrade to the latest versions of the tracer this will not apply anymore.

Please feel free to comment if you still observe an issue and I will reopen.
