### ISSUE TITLE
Being able to overwrite resource name of trace in symfony (v3)

### ISSUE THREAD

**Issue by chregu** [DataDog/dd-trace-php#343]
In some special circumstances, we'd like to set our own resource name for a trace. I tried with
```
 $rootScope = \DDTrace\GlobalTracer::get()->getRootScope();
        if (null !== $rootScope) {
            $rootSpan = $rootScope->getSpan();
            $rootSpan->setResource($name);

            $rootSpan->setTag('symfony.route.name', $name);
        }
```
But that doesn't work. The `symfony.route.name`  part does get recorded, though. Would be nice, if that would be possible.

It's with the symfony v3 bundle, didn't check for v4.

**Comment by labbati** [comment]
Hi @chregu, I think the problem is not "how" you do it (which is correct) but "when" you do it. What I bet is happening is that you do it early on in the process (e.g. in a bundle or similar) and that value is overwritten by our integration.

While we are working to improve the way we handle resources, here is a temporarily workaround that you can put in place in the meantime.

If you use a pretty much standard `web/app.php` you should have toward the end something like:

```
$response->send();
$kernel->terminate($request, $response);
```

In this case you can either move your snippet after the kernel termination or early on in the process hook into the `terminate` invocation:

```
dd_trace('Symfony\Component\HttpKernel\Kernel', 'terminate', function () {

    $rootScope = \DDTrace\GlobalTracer::get()->getRootScope();
    if (null !== $rootScope) {
        $rootSpan = $rootScope->getSpan();
        $rootSpan->setResource($name);
        $rootSpan->setTag('symfony.route.name', $name);
    }

    return call_user_func_array([$this, 'terminate'], func_get_args());
});

```

A couple of notes though:

1. We are working to make working with resource names easier in our api/configuration
2. _IMPORTANT_: It is very important that you properly set resource names. Say you have 10k users and you set as the resource name `$_SERVER('REQUEST_URI')` you would end up with 10k different resources for the very same endpoint `/users/<id>/profile`. In this case what you set as the resource name should not involve the id, e.g. `user-profile` would be ok.

**Comment by chregu** [comment]
Thanks a lot for the quick reply. Will try something in this direction.

**Comment by labbati** [comment]
Hi @chregu just checking in to know if the approach I suggested did work?

**Comment by lucasfernand-es** [comment]
> 1. We are working to make working with resource names easier in our api/configuration

Hi @labbati , we are currently facing this issue in company. Any updates in this front would would be deeply appreciated.

Having two different PHP applications running in the same environment proved to be a headache because there is not a way to track each service, from each app, properly. Currently we adopt a workaround, but it is far from _ideal_. As well as Manual Instrumentation would not be something we would be able to do.

**Comment by labbati** [comment]
Hi @lucasfernand-es 

> Having two different PHP applications running in the same environment proved to be a headache because there is not a way to track each service, from each app, properly.

Why not use `DD_TRACE_APP_NAME=app_name` with different values in order to differentiate the two apps? Am I missing something?

**Comment by lucasfernand-es** [comment]
> Hi @lucasfernand-es
> 
> > Having two different PHP applications running in the same environment proved to be a headache because there is not a way to track each service, from each app, properly.
> 
> Why not use `DD_TRACE_APP_NAME=app_name` with different values in order to differentiate the two apps? Am I missing something?

The problem is that `DD_TRACE_APP_NAME=app_name` only renames the framework, in our case Laravel.
All other resources we use, such as PDO, Curl, Guzzle (etc) share the same name in the APM dashboard. We would like to be able to differentiate those for each project. Other languages, like Ruby, have that covered by DataDog.

**Comment by labbati** [comment]
@lucasfernand-es thanks for clarifying this. What you need then is service mapping (e.g. `DD_SERVICE_MAPPING` in [Java docs](https://docs.datadoghq.com/tracing/setup/java/#configuration)).

Currently PHP does not implement this but it is scheduled to be implemented very soon. I will get back to you with an ETA asap.

**Comment by nickdgriffin** [comment]
Is DD_SERVICE_MAPPING going to make an appearance?

**Comment by labbati** [comment]
Hi @nickdgriffin, service mapping is in  the road map but we  cannot provide an ETA at the moment.

**Comment by nickdgriffin** [comment]
@labbati OK, thanks for the update

**Comment by taneishamitchell** [comment]
👍 looking forward to the addition of `DD_SERVICE_MAPPING` for php

**Comment by tonglil** [comment]
+1

**Comment by lucasfernand-es** [comment]
👍

**Comment by nickdgriffin** [comment]
`DD_SERVICE_MAPPING` looks to now be supported: https://github.com/DataDog/dd-trace-php/releases/tag/0.43.0

**Comment by labbati** [comment]
👋 hello everyone! With service mapping now released I think this issue can be closed. Feel free to reopen it if you think there is more work to be done.
