### ISSUE TITLE
Support for Laravel Job

### ISSUE THREAD

**Issue by itsDamien** [DataDog/dd-trace-php#379]
Hello,

Can DD Trace be used with Laravel Worker (Async job etc...) ?

Is this planned?

**Comment by labbati** [comment]
Hi 👋 ! Not super familiar with Laravel's Queues but in general here are some insights about CLI scripts in general.

Currently we do not trace scripts and the `CLI` SAPI in general. We just exit. We want to change this behavior and allow for tracing cli scripts. The default behavior will be no tracing on CLI by default + activation by env variable. I cannot commit to a date as of now as we have other priorities unfortunately. Of course this is up for grab 😄.

**Comment by timbroder** [comment]
Was googling and came to this ticket. Wanted to link this one for posterity https://github.com/DataDog/dd-trace-php/pull/422

**Comment by gmansilla** [comment]
@damiencriado you can trace your Workers but there are a couple of things to be aware of:

1. You must set an env var like this as CLI tracing is disabled by default.

    $DD_TRACE_CLI_ENABLED=true php artisan queue:listen 

2. A consequence of the above is that you now will have TONS of traces of "artisan" (remember this command is running constantly).

3. In order to prevent what I mentioned above you have to:

    a. blacklist "artisan" in your datadog configuration file (datadog.yaml).
    b. manually instrument your Job.

            $span = GlobalTracer::get()->getActiveSpan();
            $span->setTag(Tag::SERVICE_NAME, 'yourServiceName');
            $span->setTag(Tag::RESOURCE_NAME, 'yourResourceName');

4. (This is more of a Laravel/Lumen thing) Be aware of the difference between queue:work and queue:listen. 
Listen: bootstraps the app constantly, this means there'll be some impact in memory. But you don't have to restart the queue command whenever you update your code.
Work: bootstraps the application once (like a daemon), the downside of this is that since the application is always running you must manually flush the tracer

**Comment by brandonburkett** [comment]
This is an old one, but if we are using `work` instead of listen, do we still need to manually instrument each job (and flush)?

**Comment by gmansilla** [comment]
@brandonburkett yes.

**Comment by supernova13892** [comment]
So, I am trying to make it work with queue:work and so far have been unsuccessful.

This is my code in the handle method of Laravel Job:
`

        $tracer=\DDTrace\GlobalTracer::get();
        $newScope=$tracer->startActiveSpan('someString');
        $span=$newScope->getSpan();

        //add relevant tags
        $span->setTag('section','export');
        $span->setTag('test','1');
        
        $span->setTag('section', 'export');
        $span->setTag('client_id',$this->clientId);
        $span->setTag('initiator',$this->initiator);
        $span->setTag('request_id',$this->exportRequestId);

        //actual Work
        parent::export();

        //close scope/finish span
        $span->finish();
        $newScope->close();
        $tracer->flush();
`

But I don't get any meaningful logs. I am getting some auto generated logs which all have a duration of milliseconds and none of them have these tags.

Also, worth nothing is **when I add tags to the root span, I do get these tags, but I get logs only once per process**.

**Comment by aleferreiranogueira** [comment]
@saranshdhingra hello there, we've experiencing the same issue as you

We've tried to set spans on Laravel's Queue listeners events on before and after the job runs whilst setting the `DD_TRACE_AUTO_FLUSH_ENABLED=true` and `DD_TRACE_GENERATE_ROOT_SPAN=false` as [per documentation](https://docs.datadoghq.com/tracing/setup_overview/setup/php/?tab=containers#environment-variable-configuration)|

We're using **ddtrace** **0.60**

Did you had any success on tracing laravel `queue:work`?

Thanks a lot
