### ISSUE TITLE
call_user_func and call_user_func_array don't work correctly with Namespace 

### ISSUE THREAD

**Issue by icharlie** [DataDog/dd-trace-php#443]
When using call_user_func or call_user_func_array to call another class method in a class with a namespace, the dd_trace's callable function does not get invoked correctly, but a direct method call does run correctly.

Test on:
php: 7.1.19 and 7.2.14
ddtrace: 0.23.0 and 0.17.0

    <?php
    namespace Test;
    
    dd_trace('Test\B', 'get', function () {
      return 'Get B'.PHP_EOL;
    });
    
    
    class A {
        private $b;
    
        public function __construct()
        {
            $this->b = new B;
        }
    
        public function get($name)
        {
          // This returns "Get test" (incorrect)
          // return call_user_func([$this->b, 'get'], $name);
          
          // This returns "Get B"(correct)
          return $this->b->get($name);
        }
    };
    
    class B {
      public function get($argument)
      {
        return "Get {$argument}".PHP_EOL;
      }
    }
    
    $a = new \Test\A;
    echo $a->get('test');

**Comment by SammyK** [comment]
Thanks so much for the report, @icharlie! I wanted to let you know we have this on our radar and will dig into more detail as soon as we can. :)

**Comment by morrisonlevi** [comment]
The root of this issue is that the opcodes are different because `call_user_func` was not used by its fully qualified name. If the fully qualified name is used, then `call_user_func([$this->b, 'get'], $name)` is basically the same as `$this->b->get($name)` at the opcode level and so it works.

If it's not fully qualified, then it uses different opcodes. It has to do this because it's possible `\Test\call_user_func` exists and wouldn't actually call `\call_user_func`. We don't currently support calls that go through the actual `call_user_func` function, which also affects PHP 5.

**Comment by morrisonlevi** [comment]
This was fixed in PHP 5 in version 0.48.0; it still exists in our tracer for PHP 7.

**Comment by tmotyl** [comment]
@morrisonlevi is it possible to instrument call_user_func or call_user_func_array to add a span with whatever its calling?
I'm using https://github.com/Luracast/Restler which invokes controller action using call_user_func_array so I would like to have a span with the controller action shown.

**Comment by morrisonlevi** [comment]
@tmotyl Fixing this is in the backlog and I'm not sure when it will get prioritized. The fastest way for you to get support is to patch Luracast/Restler to use fully qualified function names e.g. `\call_user_func` and `\call_user_func_array`. I know that's probably not what you were hoping to hear, but at least there is an actionable workaround.

**Comment by bwoebi** [comment]
I'm closing this issue as it's obsolete, given that dd_trace() has been made a no-op in 0.48.0.

**Comment by tmotyl** [comment]
@bwoebi Have you checked if the issue doesn't occur with \DDTrace\trace_method( or \DDTrace\trace_function( ?
When I was testing it, I was using `\DDTrace\trace_function(` and not `dd_trace`
So it might not be solved yet.

**Comment by bwoebi** [comment]
Actually, you are right :-) Reopening now. Let me investigate now whether I can fix this.

**Comment by bwoebi** [comment]
Turns out scope resolution is not correct here. I'll create a PR for this.

**Comment by bwoebi** [comment]
Overall, the fundamental problem is `zend_call_function`.

There are a couple approaches to solve the problem, none of them great.

a) _In `zend_execute_internal` point EG(vm_stack_top) to write-protected memory and intercept the segfault, then check the attempted value written (it'll be the zend_function pointer)._ Not reasonable to do.
b) _In `zend_execute_internal` swap `zend_execute_ex` with a custom handler and swap back on invocation of that handler._ Good solution, but NTS only.
c) _Globally swap `zend_execute_ex` with a custom handler._ Has overhead on every single userland function call. Additionally allows for stack overflows when userland does recursion.
d) _Add a custom opcode during compilation at every function start which checks the tracing of the function (instead of fcall/ucall/do_fcall opcode overloads)._ Sort of reasonable, but plays badly with file opcode caching.
e) _Instrument execute_ex at the machine code level._ Sort of possible, given that we only support amd64 currently, but overall meh.
f) _Duplicate op_array opcodes upon instrumenting and insert our own custom opcode there._ Probably reasonable, but needs quite some things to check.

**Comment by bwoebi** [comment]
@tmotyl We target fixing this in a future release (in the next 1-2 months), but we are not quite there yet.

**Comment by bwoebi** [comment]
@tmotyl This has been fixed with the recent 0.76.0 release.

It took quite a while, but now it's done!
