### ISSUE TITLE
Type exception is thrown when calling extract(Format::TEXT_MAP, $carrier)

### ISSUE THREAD

**Issue by drupsys** [DataDog/dd-trace-php#463]
I'm getting the following exception when extracting trace information from a text payload
```
In InvalidSpanOption.php line 47:

Invalid child_of option. Expected Span or SpanContext, got DDTrace\OpenTracer\SpanContext                                                                                               
```

I'm pretty sure this is a bug in the package, you can try to replicate this using the following details.

Packages: `opentracing/opentracing:1.0.0-beta6` and `datadog/dd-trace:0.26.0`

Carrier in the payload:
`{"x-datadog-trace-id":"2409624703365403319","x-datadog-parent-id":"2409624703365403319","x-datadog-sampling-priority":1}`

Code used to extract the span from payload:
```
$tracer = GlobalTracer::get();
$carrier = \GuzzleHttp\json_decode($headers['carrier'], true);
$context = $tracer->extract(Format::TEXT_MAP, $carrier);
$span = $tracer->startSpan(Span::FIND_PLATFORM_CAMPAIGN_CHANGES, ['child_of' => $context]);
```

The error originates from the fact that `buildChildOf(...)` function in `DDTrace\StartSpanOptions` class (line 184) checks if the `$context` instance implements `DDTrace\Contracts\Span` or `DDTrace\Contracts\SpanContext` but the context is of type `DDTrace\OpenTracer\SpanContext` and it does not appear to implement either one of those interfaces.

`dd($context);` output is:
```
DDTrace\OpenTracer\SpanContext {#1177
  -context: DDTrace\SpanContext {#1178
    +traceId: "2409624703365403319"
    +spanId: "2409624703365403319"
    +parentId: null
    +isDistributedTracingActivationContext: true
    +propagatedPrioritySampling: null
    +parentContext: null
    +baggageItems: []
  }
}
```

**Comment by drupsys** [comment]
The following script can be used to replicate the issue

Running on `php 7.1` with  `opentracing/opentracing:1.0.0-beta6` and `datadog/dd-trace:0.26.0`

```
<?php

use DDTrace\Format;
use DDTrace\OpenTracer\Tracer;
use OpenTracing\GlobalTracer;

require __DIR__ . '/vendor/autoload.php';

// Setup global tracer
$options = ['service_name' => 'magic_app'];
GlobalTracer::set(Tracer::make(null, null, $options));

$tracer = GlobalTracer::get();

// Create a carrier to transmit trace/span id over wire
$A = $tracer->startActiveSpan('A')->getSpan();
$tracer->inject($A->getContext(), Format::TEXT_MAP, $carrier);

// Create a span from carrier
$context = $tracer->extract(Format::TEXT_MAP, $carrier);
$B = $tracer->startActiveSpan('B', ['child_of' => $context]); // This line will throw an exception

```

**Comment by labbati** [comment]
Hi @drupsys, thanks for your patience.

Our architecture is not designed to supprot your usage. You should not set the `GlobalTracer`. We do it for you. But you can use it of course, in order to manual instrumentation.

For example, you can access it from `OpenTracing\GlobalTracer::get()` and you will obtain a OT tracer (i.e. implementing the OT Tracer interface) which under the hood uses our own tracer.

I noticed in the example above that you wanted to set the service name and probably that was the motivation why you tried to set your own tracer. For that we provide [env variables](https://docs.datadoghq.com/tracing/setup/php/#configuration) which at the moment is the only approach we support. In your case `DD_SERVICE_NAME`.

If what I mentioned above does not cover your use case, please get back to us and we can discuss how we can help.

**Comment by drupsys** [comment]
Hi @labbati, could you clarify what you mean by "We do it for you" in "Our architecture is not designed to support your usage. You should not set the GlobalTracer. We do it for you. But you can use it of course, in order to do manual instrumentation."?

At the moment if I don't set global tracer then `OpenTracing\GlobalTracer::get()` returns an instance of `OpenTracing\NoopTracer` instead of an instance of `DDTrace\OpenTracer\Tracer`. My setup is based on OpenTracing documentation, if DataDog is not following the OpenTracing standard setup procedure then could you give me an example of how to set it up? Since I could not find any documentation on this I thought that you are just following the standard.

**Comment by labbati** [comment]
Hi

> At the moment if I don't set global tracer then OpenTracing\GlobalTracer::get() returns an instance of OpenTracing\NoopTracer

then this is a different problem, auto-instrumentation in not working in your case. Because you should receive the instance that we preset.

A couple of things here:

1. [For all SAPI] Make sure that `php -i | grep ddtrace` returns a property `ddtrace.request_init_hook` with the path to an existing file in our installation directory (if you used one of our supported packages) or if you installed it manually to `<WHERE_YOU_EXTRACTED_PACKAGE>/opt/datadog-php/dd-trace-sources/bridge/dd_wrap_autoloader.php`.
2. [only for CLI scripts] the above should be fixing your issue if you are using a non-CLI SAPI (e.g. serving pages through apache). On the other hand, we are [off by default](https://docs.datadoghq.com/tracing/setup/php/#cli-library-compatibility) in CLI apps. In this case all you have to do is setting an env, e.g. inline as in `DD_TRACE_CLI_ENABLED=true php script.php`
3. Also note that we use autoloader registration as a hook for auto-instrumentation, which BTW is your case so you are good to go

**Comment by drupsys** [comment]
Thank you, now I understand what [this](https://docs.datadoghq.com/tracing/setup/php/) part of the documentation was about, however, I have one specific use case which I don't think is covered by auto-instrumentation so I have one last question.

In our project our services communicate to each other with events (primarily AWS SQS messages) if I'm not mistaken these would not be automatically instrumented. This is the reason why I was trying to serialise trace ids into a format that I could send over the wire. The idea was to make produces attach trace ids to each event so that consumers could recreate the trace on their end. Is there any way for me to manually transfer traces over the wire?

The above is kind of a critical requirement for us, we can't fully benefit from tracing if it is not possible.

**Comment by labbati** [comment]
I am not familiar with AWS SQS, but what you are describing makes sense to me. Can you explain how you push events to SQS and how you find new events to process from SQS? We might be missing one part to support this use case, assuming that this is not pure HTTP requests.

1. From the OT tracer that we return you have access to the current span and hence to the current span context.
2. you can use the `$tracer->inject($context, 'text_map', $arrayPassedByReference)`
3. then you will have in the `$arrayPassedByReference` the trace id and the, and span id that you store into the event.
4. [this is the part we might be missing] On the event receiver (don't know how it works but I assume it is a script with a callback?) in that case you do `$tracer->startActiveSpan('my_operation_name', ['child_of' => <context from event> ]);`

**Comment by drupsys** [comment]
The above is exactly what I've tried to do, however, this `$tracer->startActiveSpan('my_operation_name', ['child_of' > => <context from event> ])` throws an exception `DDTrace/Exceptions/InvalidSpanOption with message 'Invalid child_of option. Expected Span or SpanContext, got DDTrace/OpenTracer/SpanContext'` as explained in my initial post.

Just to be clear I've tried this after I fixed auto-instrumentation, the above approach is still not working and breaks in the exact same way it did initially.

**Comment by drupsys** [comment]
@labbati I found the cause of the bug and I also know how to fix it. 

The issue is that `$context = $tracer->extract(Format::TEXT_MAP, $carrier);` returns a `context` that is wrapped within `DDTrace\OpenTracer\SpanContext` and it is not one of the valid inputs for the `child_of` option in `$tracer->startActiveSpan('my_operation_name', ['child_of' => $context ])`.

A simple solution is to allow this type for a `child_of` option in `src/DDTrace/StartSpanOptions.php` file.

```
    private static function buildChildOf($value)
    {
        ...
        if ($value instanceof DDTrace\OpenTracer\SpanContext) {
            return Reference::create(Reference::CHILD_OF, $value->unwrapped());
        }

        throw InvalidSpanOption::forInvalidChildOf($value);
    }
```

`$value` in the above code snipped is the wrapped `$context`.

Do you think someone on your end could fix this bug?

**Comment by morrisonlevi** [comment]
As part of the [0.36.1 release](https://github.com/DataDog/dd-trace-php/releases/tag/0.36.1), this fix has been applied. When you get a moment, can you update and verify that it is working for you?

**Comment by drupsys** [comment]
Thanks, I'll take a look at this when I'm back in office next week.

**Comment by morrisonlevi** [comment]
We believe this has been fixed and are closing the issue. If you find that you still have the problem after upgrading to 0.36.1 or newer, please re-open the issue.
