### ISSUE TITLE
Not able to get log of laravel application in /var/log/datadog/trace-agent.log

### ISSUE THREAD

**Issue by ask664** [DataDog/dd-trace-php#535]
showing this error for check status of datadog
=> $ sudo datadog-agent status
==========
Logs Agent
==========
    LogsProcessed: 0
    LogsSent: 0

  apache
  ------
    Type: file
    Path: /var/log/apache2/access.log
    Status: Error: file /var/log/apache2/access.log does not exist
    Type: file
    Path: /var/log/apache2/error.log
    Status: Error: file /var/log/apache2/error.log does not exist

**Comment by labbati** [comment]
Hi @ask664 thanks for reporting this. Trying to help as much as you can even if probably you'd have a better chance reaching out to our [support team](https://www.datadoghq.com/support/).

I assume that you setup the datadog agent to read logs from a Laravel application that you are instrumenting and that is configured to emit logs to apache.

I have a few questions:

1. do files actually exists? If they DO exist then this is definitely an issue with the agent's log reader and I suggest you to open a ticket with our support, otherwise keep reading :)
2. if you remove the dd-trace-php extension do logs show up in the files? If yes then we need to know a little bit more about your apache + php setup (including configuration) as this would be definitely a first time that we hear such a thing.
3. if not then this should be an issue with how you configure apache.

**Comment by ask664** [comment]
1. Yes, the apache log file exists.
2. there is simple apache2 with php7.1 configuration. I already added dd-trace-php apache configuration php.ini file.

**Comment by labbati** [comment]
> Yes, the apache log file exists.

then please reach out to the [support team](https://www.datadoghq.com/support/) and please link this issue as well. This seems to be related to some agent/log misconfiguration or some other issue.

I am closing this issue for now. If you believe that I misinterpreted something please feel free to re-open and comment on it
