### ISSUE TITLE
PECL release with no change

### ISSUE THREAD

**Issue by remicollet** [DataDog/dd-trace-php#619]
Is there a reason release new version on PECL when no change

At least:

* 0.33.0
* 0.32.1

And especially with a wrong changelog (changes in the library)

**Comment by SammyK** [comment]
Very good point @remicollet!

@morrisonlevi @labbati From the PECL perspective, when we make a release with no extension changes, it technically doesn't impact PECL installs at all. Since we currently can't ship the userland changes in PECL anyway, what do you all think about only releasing on PECL when there are changes to the extension?

**Comment by morrisonlevi** [comment]
Assume we only release PECL changes when there are changes to the ext; would our version numbers then diverge? Or would we just leave holes in the versions?

**Comment by remicollet** [comment]
Leaving holes in the versions seems the simplest.

**Comment by SammyK** [comment]
We will only release on PECL if there are changes to the extension. Thanks again for pointing this out @remicollet! :)
