### ISSUE TITLE
Tracing with async/CLI setups

### ISSUE THREAD

**Issue by SonarSoftware** [DataDog/dd-trace-php#704]
I'm currently using Swoole, but I'm guessing it's a similar issue for ReactPHP. Is there any direction on getting it working on an environment like this today? Or any plans to implement?

**Comment by labbati** [comment]
Hi @SonarSoftware, we definitely have plans for ReactPHP as it came up a few times now, and I guess a similar solution might apply to Swoole as well, as you are suggesting.

I cannot provide an ETA at the moment, though. Given that I am not expert about RactPHP/Swoole internals (I only can assume that there is some separate thread/event loop under the hood) this would make it difficult for you to support tracing without some work on our side due to the following reasons that comes to my mind (@SammyK and @morrisonlevi feel free to jump in as you might have more experience than me with those libraries):

- at the moment we flush traces on a `register_shutdown_function`. This would not work in your case as your script (I assume) runs as long as the app runs.
- Even if you manual invoke `GlobalTracer::get()->flush()` in some `after-response` hook that is provided by Swoole/ReactPHP, the Tracer remains in an unpredictable state as it approaches serving next request.
- On top of that, and this might be the really tricky part, We use at the moment one global tracer instance (as per [OpenTracing](https://opentracing.io/) approach) and span coming from different requests I am pretty sure would end up mixed in a giant basket.

Again, I have never used such libraries so I can only talk from the top of my head.

**Comment by SonarSoftware** [comment]
Yes, it is tricky. There are some ways around the global tracer issue - Swoole for example has a sandbox that is used to separate per-request items out. That being said, it's still not easy and it would definitely take some work.

It might be worth taking a look at https://github.com/upscalesoftware/swoole-newrelic for some inspiration - I've been poking at it a bit seeing if we can do something similar with ddtrace.

**Comment by nesl247** [comment]
Any update on this? I ask because we are in the process of migrating from NewRelic and ran into this. It is not an issue we expected to show up.

**Comment by morrisonlevi** [comment]
I am not aware of any updates specific to ReactPHP or Swoole, but I know some of the underlying engineering challenges that assume a single global trace are being worked on.

One thing to set expectations on is _what_ in these products gets traced. To that end you could help by sharing what features you are using. As an example, I found a `React\Http\Server` class -- I assume that users would want each new request that the server processes to get traced independently. Telling us which pieces of Swoole and ReactPHP are being used can help us know where to look in docs, examples, etc when this work gets prioritized.

**Comment by nesl247** [comment]
I believe we're using `Swoole v4.4.15` at this time with PHP `7.4`. And yes, we would expect each new request that swoole processes to be traced independently.

**Comment by SonarSoftware** [comment]
Yep, exactly. Just treat each request as independent. I think this might be fairly easy to do by hooking into the `onRequest` method.. I'm planning to take a look at this myself soon.

**Comment by mrtus** [comment]
HI @morrisonlevi @labbati Could you provide us with an update on the work being done to make this possible?

And would it maybe be possible to elaborate a little bit more on this:
> Even if you manual invoke GlobalTracer::get()->flush() in some after-response hook ..., the Tracer remains in an unpredictable state as it approaches serving next request.

As I'm currently looking into getting our distributed services through queueing connected to each other with tracing (we already have our logs connected through the same way with a `trace_id` property). I would, just like it is already done with curl, attach the tracing data on the message when published and get that data from the message when consumed by a long running process worker. After this message is consumed, I would of course want to call a `flush`, but I'm reading here that the tracer would be in an unpredictable state. Can you elaborate what you mean with `unpredictable`, what are the side-effects of this, and would there be some sort of remenand traces that would tie multiple messages together?

**Comment by anderson-flores** [comment]
Hi, any updates about this feature? 

Thanks!

**Comment by labbati** [comment]
Hi @anderson-flores! At the moment we were not able to schedule the work for this and we cannot commit to a specific timeline. We will update as soon as possible.

**Comment by wregis** [comment]
I guess I've got a similar problem with Laravel Horizon running for days on a server. It would be nice to trace jobs individually.

**Comment by bwoebi** [comment]
We do not yet have concrete updates on this, except that it is on our roadmap by now (we expect some actual results regarding async surfacing this year) and new APIs are being designed with async in mind (e.g. the usage of a span stack like we currently have is inherently incompatible with async use cases).

**Comment by elijahchancey** [comment]
We'd really really love to have this!

**Comment by chrisbradleydev** [comment]
Any news on tracing for Laravel Octane Swoole?

**Comment by bwoebi** [comment]
I sadly have to repeat what I said in February. Hopefully basic fiber support, including simple async support will land within a couple months. Only then, we will be able to look into laravel octane or swoole.

**Comment by chrisbradleydev** [comment]
@bwoebi, thanks for the quick reply.

**Comment by egonbraun** [comment]
Quick question, is this support with RoadRunner instead of Swoole? Or is this not support due to the async nature of Laravel?

**Comment by donparapidos** [comment]
@bwoebi any news on this, in few weeks it will be 3 years since initial question ? quite some time

**Comment by morrisonlevi** [comment]
In PHP 0.82.0, we added a Roadrunner integration: DataDog/dd-trace-php#1813. Bob will be unavailable until the New Year, and I am filling in as best as I can. I don't know what's on the roadmap, or what's blocking more Async/CLI setups, sorry!

**Comment by githubeto** [comment]
I set up ddtrace 0.82.0 in the Laravel Octane (Roadrunner) application,
but still no trace data was output to APM. Does that mean that 0.82.0 is still not supported?
And also, when do you plan to release?

**Comment by bwoebi** [comment]
Hey @githubeto,
Minimal tracing data about the requests occurring should appear since 0.82.0 with Laravel Octane running on roadrunner.
I'd like to ask whether you did enable CLI? Roadrunner is spawning CLI processes, which needs to be explicitly enabled in ini via `datadog.trace.cli_enabled=1` (or `DD_TRACE_CLI_ENABLED=1` env var).

**Comment by githubeto** [comment]
@bwoebi ,
appreciate your quick reply.
I had already set DD_TRACE_CLI_ENABLED=true in my Docker laravel application.
Extract a part of the dockerfile.

- dockerfile (laravel application)
```
RUN curl -LO https://github.com/DataDog/dd-trace-php/releases/latest/download/datadog-setup.php
RUN php datadog-setup.php --php-bin=all

ENV DD_TRACE_CLI_ENABLED true
ENV DD_TRACE_GENERATE_ROOT_SPAN false
ENV DD_TRACE_AUTO_FLUSH_ENABLED true
ENV DD_TRACE_GENERATE_ROOT_SPAN true
ENV DD_TRACE_ANALYTICS_ENABLED true
ENV DD_TRACE_LARAVEL_ENABLED true
```

This is an application running on AWS Fargate, and the task definition also includes the following settings.

- laravel application container

```
                {
                    "name": "DD_ENV",
                    "value": "infra"
                },
                {
                    "name": "DD_SERVICE",
                    "value": "api"
                },
                {
                    "name": "DD_VERSION",
                    "value": "beta"
                },
```

- datadog agent container
```
               {
                    "name": "DD_SITE",
                    "value": "datadoghq.com"
                },
                {
                    "name": "DD_PROCFS_PATH",
                    "value": "/proc"
                },
                {
                    "name": "DD_APM_NON_LOCAL_TRAFFIC",
                    "value": "true"
                },
                {
                    "name": "DD_APM_ENABLED",
                    "value": "true"
                },
                {
                    "name": "ECS_FARGATE",
                    "value": "true"
                },
                {
                    "name": "DD_LOGS_ENABLED",
                    "value": "true"
                },
                {
                    "name": "DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL",
                    "value": "true"
                },
                {
                    "name": "DD_CONTAINER_EXCLUDE",
                    "value": "name:datadog-agent"
                },
                {
                    "name": "DD_PROCESS_AGENT_ENABLED",
                    "value": "true"
                },
                {
                    "name": "DD_APM_ENV",
                    "value": "infra"
                }

~~~

            "secrets": [
                {
                    "name": "DD_API_KEY",
                    "valueFrom": "xxxxxxxxxxxxx"
                }
            ],
```

If I change the application server configuration to nginx + php-fpm instead of laravel octane(roadrunner),
tracing data about the requests occurring appear, so I think the settings I wrote above are fine.

**Comment by bwoebi** [comment]
OpenSwoole does not provide an API for tracking context switches. (Development seems also to be relatively quiet there.)

With Swoole, we're targeting next quarter to have a closer investigation and possibly actual support.

**Comment by carlosevieira** [comment]
Any updates on this @bwoebi  ?
I just migrated from php-fpm to Swoole, but I'm just missing datadog :/

**Comment by GuillaumeBrook** [comment]
Same question, @bwoebi, any progress has been made in Swoole support ?

**Comment by carlosevieira** [comment]
4 years of no support for one of the popular deployment stacks for PHP applications,
maybe this year we will have support for Swolle? @bwoebi @estringana  :(

I can't believe a company like Datadog is ignoring this...

**Comment by bwoebi** [comment]
@carlosevieira Looks like we will have it soon :-)

**Comment by PROFeNoM** [comment]
Hi everyone :wave:

The [0.99.0](https://github.com/DataDog/dd-trace-php/releases/tag/0.99.0) release of the PHP Library added support for Swoole 🎉 

Upgrading to the latest version of the tracer will create a trace for each individual request made to Swoole HTTP Servers without you having to perform any manual instrumentation.

Should any issue arise, we encourage you to open a new [Github Issue](https://github.com/DataDog/dd-trace-php/issues) or contact our [Support Team](https://www.datadoghq.com/support/) for assistance.

We greatly appreciate your patience :pray:

**Comment by sneycampos** [comment]
Thansk for the release @PROFeNoM! 
Could you share any instructions to instrumentate the application with Laravel Octane running on Swoole?

Setting php.ini?

**Comment by PROFeNoM** [comment]
Hi @sneycampos :wave:

Typically, if you already have a Laravel Octane w/ Swoole app, you only have to upgrade the tracer.

If the service is not yet instrumented, then you would have to [download and install](https://docs.datadoghq.com/tracing/trace_collection/automatic_instrumentation/dd_libraries/php/#install-the-extension) the tracer and forward it to your [datadog-agent](https://docs.datadoghq.com/getting_started/agent/).

---

I'll now give an example if this can help you out.
Following the official documentation of Laravel Octane, let's say you have set up your application with Laravel Sail. You'll certainly have a `docker/` directory or such with your various Dockerfiles. To install the tracer, you would add the following two lines to your Dockerfile:
```sh
curl -LO https://github.com/DataDog/dd-trace-php/releases/latest/download/datadog-setup.php
# APM only
php datadog-setup.php --php-bin=all
```

and in your `docker-compose.yml`, you'd typically have to add at the very least the following environment variable to your Laravel service:
```yaml
DD_TRACE_CLI_ENABLED: true
DD_AGENT_HOST: datadog-agent
```
and a `datadog-agent` service:
```yaml
  datadog-agent:
    image: datadog/agent:latest
    container_name: datadog-agent
    environment:
      DD_API_KEY: <YOUR_API_KEY>
      DD_SITE: <YOUR_DD_SITE>
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
```

I extracted the above snippets from a sample Laravel Octane app with Swoole of mine, so that's just an example. It will ultimately depend on the specifics of your services, though.

---

I'm happy to answer any specific questions you may have. If you are having trouble instrumenting your app, I greatly encourage you to either contact our Support Teams or create a GitHub Issue.

**Comment by PROFeNoM** [comment]
Hi @sneycampos 

Thanks for coming up with all this information.

> I'm using the FROM openswoole/swoole:22.1.1-php8.3-alpine image

I'm afraid this is the root cause of your issue. Your image uses [OpenSwoole](https://github.com/openswoole/ext-openswoole), while our tracing library provides support for [Swoole](https://github.com/swoole/swoole-src).

As of today, it is not possible to provide support for OpenSwoole because it does not support Fibers, which are required for proper tracing and interception.

When it comes to Laravel Octane, we are supporting:
- FrankenPHP
- Roadrunner
- Swoole (which does not include OpenSwoole)

Until OpenSwoole makes changes on their side, I'm afraid there is nothing that can be done on our side to provide proper support for OpenSwoole :(

**Comment by sneycampos** [comment]
@PROFeNoM Thank you! 
I'll replace the image to use Swoole's and give you a feedback :)

**Comment by sneycampos** [comment]
@PROFeNoM could you share any dockerfile/docker-compose with agent and octane working? i tried with your repository (https://github.com/PROFeNoM/octane-demo/blob/main/docker-compose.yml) and didn't work too
