### ISSUE TITLE
Latest or stable tag

### ISSUE THREAD

**Issue by thiagocordeiro** [DataDog/dd-trace-php#810]
**Describe the solution you'd like**
Would be good to have a `latest` or `stable` tag so we could setup this on our docker file instead of a fixed version

**Comment by labbati** [comment]
Hi @thiagocordeiro, and sorry for the late reply. Let us discuss this. In the meantime would something like the code below work for you?

```
curl -s https://api.github.com/repos/Datadog/dd-trace-php/releases/latest \
| grep "browser_download_url.*deb" \
| cut -d : -f 2,3 \
| tr -d \" \
| wget -O dd-trace-php.deb -qi -
```

**Comment by gsomoza** [comment]
You can do this easily if you make sure the assets that are released have a fixed file name instead of including the version number : https://help.github.com/en/github/administering-a-repository/linking-to-releases

E.g. this link would work right now but not after the next release:  https://github.com/DataDog/dd-trace-php/releases/latest/download/datadog-php-tracer_0.46.0_amd64.deb

So instead if the asset was called `datadog-php-tracer_amd64.deb` then the link would be https://github.com/DataDog/dd-trace-php/releases/latest/download/datadog-php-tracer_amd64.deb and it would never break.

**Comment by gsomoza** [comment]
To implement this I would recommend keeping the old format but ALSO adding a copy of the release without the version number in the filename, along with a deprecation warning for the old naming scheme. Then old scripts keep working while new scripts benefit from the improvement. It would mean double the assets released for a few versions but probably worth it.

**Comment by burizz** [comment]
It is hard to automate this when there is no latest tag. Will be great if this is added.

**Comment by bwoebi** [comment]
With our new installer, https://github.com/DataDog/dd-trace-php/releases/download/latest/datadog-setup.php is usable and will always point to the latest version. This should solve this issue :-)
