### ISSUE TITLE
Custom instrumentation difficulties

### ISSUE THREAD

**Issue by vidalvasconcelos** [DataDog/dd-trace-php#959]
Hey, guys I don't know if is right place for questions, but we are using this [docs](https://docs.datadoghq.com/tracing/custom_instrumentation/php/?tab=tracingfunctioncalls#opentracing) as a guide but it is leaving us confused.

Some parts of our stack are not yet covered by automatic instrumentation, so we opted for opentracing, but even installing the library by composer and extension being available, these followed lines throw an error as if this class `\DDTrace\OpenTracer\Tracer` didn't exist or don't loaded by composer.
```php
$otTracer = new \DDTrace\OpenTracer\Tracer(\DDTrace\GlobalTracer::get());
```

We currently using version.0.47.0 and I think I'm missing a step in the installation, can someone help me?

**Comment by labbati** [comment]
Hi @vidalvasconcelos a couple of comments.

The snippet in the docs seems correct to me. I just tested and generated spans for me. Example:

```
$otTracer = new \DDTrace\OpenTracer\Tracer(\DDTrace\GlobalTracer::get());
\OpenTracing\GlobalTracer::set($otTracer);
$span = $otTracer->startActiveSpan('my.span')->getSpan();
$span->setTag('resource.name', 'my_resource');
$span->setTag('span.type', 'custom');
$span->finish();
```
So I suggest to check the following points:
1. `opentracing/opentracing: 1.0.0-beta6` is installed in your composer. Not we are not compatible with 0.* line.
2. The ddtrace extension is installed.

If the above applies can you please provide us with the exact error from the command line?

Example of trace generated with the snippet above
![image](https://user-images.githubusercontent.com/2952352/87408465-c9040580-c5c3-11ea-9b2a-12bdf72ce763.png)

**Comment by vidalvasconcelos** [comment]
@labbati Thanks for the prompt response. 
We use `Laravel 5.7.*` and when it is running a command like `php artisan tinker` as a test if everything is ok, this throw this error.

>   Class 'DDTrace\OpenTracer\Tracer' not found

I don't understand how I can access this namespace `DDTrace\OpenTracer` classes if it isn't register in the composer.json, I have created a shortcut to load this classes.

```php
// bootstrap/autoload.php 
require __DIR__.'/../vendor/datadog/dd-trace/src/DDTrace/autoload.php';
```
But I think that isn't the right solution.

**Comment by labbati** [comment]
As of today `DDTrace\OpenTracer` namespace is provided by the extension, not by the composer package. So the extension must be installed and enabled for the class to exist.

I understand this is not very usable, especially because the purpose of the separation between public api and internal classes was letting users to have access to the publicly available classes when the extension is not installed.

I suggest the following plan:

- _temporarily workaround_: Please use our `\DDTrace\GlobalTracer::get()` in place of `\OpenTracing\GlobalTracer::get()` for now which has an OT compliant (same method names) interface and it will be very easy to move to OT after we implement the mid term. If you look at the two interfaces you will notice it will be quite easy to move then the `use` statement from `DDTrace` to `Opentracing` with same method names.
- _long term_: let me get back to you with an ETA to move that namespace to the public API so you can use 100% the OT namespace with no lock in.

**Comment by vidalvasconcelos** [comment]
@labbati thank you very much for you help. 
We forget the env `DD_TRACE_CLI_ENABLED` this turn possible `artisan commands`
